# Accessing Pixel
---

In [9]:
import cv2
import numpy as np

In [10]:
img = cv2.imread('./data/lena.jpg')  # cv2.IMREAD_COLOR

print('img.ndim=', img.ndim)  # 차원
print('img.shape=', img.shape)
print('img.dtype=', img.dtype)

## np.bool, np.uint16, np.uint32, np,float32, np.float64, np.complex64
img = img.astype(np.int32)
print('img.dtype=', img.dtype)

img = np.uint8(img)
print('img.dtype=', img.dtype)

img.ndim= 3
img.shape= (512, 512, 3)
img.dtype= uint8
img.dtype= int32
img.dtype= uint8


In [11]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
print('img.shape=', img.shape)

## img = img.flatten()  # 2차원의 이미지를 1차원으로 늘리는 함수
img = img.reshape(img.shape[0] * img.shape[1])  # 1차원으로 변경(width * height)
print('img,shape=', img.shape)

img = img.reshape(512, 512)
print('img.shape=', img.shape)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

img.shape= (512, 512)
img,shape= (262144,)
img.shape= (512, 512)


In [12]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
# (200,100)에 밝기값을 0으로 설정
img[100, 200] = 0  # 화소값(밝기, 그레이스케일) 변경
print(img[100:100, 200:210]) # ROI 접근

## C/C++ Style
## for y in range(100, 400):
##     for x in range(200, 300):
##          img[y, x] = 0

## Python Style
img[100:400, 200:300] = 0   # ROI 접근
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

[]


In [13]:
img = cv2.imread('./data/lena.jpg')  # cv2.IMREAD_COLOR
img[100, 200] = [255, 0, 0]  # 컬러(BGR) 변경
print(img[100, 200:210])  # ROI 접근

## for y in range(100, 400):
##     for x in range(200, 300):
##          img[y, x] = [255, 0, 0,]   # 파랑색(blue)으로 변경

img[100:400, 200:300] = [255, 0, 0]  # ROI 접근

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

[[255   0   0]
 [116 115 207]
 [120 116 211]
 [107 103 198]
 [119 121 209]
 [116 118 206]
 [115 114 206]
 [112 111 203]
 [104 105 195]
 [110 112 200]]


In [14]:
img = cv2.imread('./data/lena.jpg')  # cv2.IMREAD_COLOR

## for y in range(100, 400):
##     for x in range(200, 300):
##          img[y, x, 0] = 255   # B-채널을 255로 변경

img[100:400, 200:300, 0] = 255 # B-채널을 255로 변경
img[100:400, 300:400, 1] = 255 # G-채널을 255로 변경
img[100:400, 400:500, 2] = 255 # R-채널을 255로 변경

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()