# General Filtering

In [2]:
import cv2
import numpy as np

In [5]:
src = cv2.imread('./data/rect.jpg', cv2.IMREAD_GRAYSCALE)
## src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

#1
kx, ky = cv2.getDerivKernels(1, 0, ksize=3)
sobelX = ky.dot(kx.T)
print('kx=', kx)
print('ky=', ky)
print('sobelX=', sobelX)
gx = cv2.filter2D(src, cv2.CV_32F, sobelX)
## gx = cv2.sepFilter2D(src, dv2.CV_32F, kx, ky)

#2
kx, ky = cv2.getDerivKernels(0, 1, ksize=3)
sobelY = ky.dot(kx.T)
print('kx=', kx)
print('ky=', ky)
print('sobelY=', sobelY)
gy = cv2.filter2D(src, cv2.CV_32F, sobelY)
## gy = cv2.sepFilter2D(src, dv2.CV_32F, kx, ky)

#3
mag = cv2.magnitude(gx, gy)
ret, edge = cv2.threshold(mag, 100, 255, cv2.THRESH_BINARY)

cv2.imshow('src', src)
cv2.imshow('edge', edge)
cv2.waitKey()
cv2.destroyAllWindows()

kx= [[-1.]
 [ 0.]
 [ 1.]]
ky= [[1.]
 [2.]
 [1.]]
sobelX= [[-1.  0.  1.]
 [-2.  0.  2.]
 [-1.  0.  1.]]
kx= [[1.]
 [2.]
 [1.]]
ky= [[-1.]
 [ 0.]
 [ 1.]]
sobelY= [[-1. -2. -1.]
 [ 0.  0.  0.]
 [ 1.  2.  1.]]


In [14]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

#1
def logFilter(ksize=7):
    k2 = ksize//2
    sigma = 0.3*(k2-1) + 0.8
    print('sigma=', sigma)
    LoG = np.zeros((ksize, ksize), dtype=np.float32)
    for y in range(-k2, k2+1):
        for x in range(-k2, k2+1):
            g = -(x*x+y*y) / (2.0+sigma**2.0)
            LoG[y+k2, x+k2] = -(1.0+g)*np.exp(g)/(np.pi*sigma**4.0)
    return LoG

#2
kernel = logFilter()  # 7, 15, 31, 51
print(kernel)
LoG = cv2.filter2D(src, cv2.CV_32F, kernel)
cv2.imshow('src', src)
cv2.imshow('LoG', LoG)
cv2.waitKey()
cv2.destroyAllWindows()

sigma= 1.4
[[ 0.00311849  0.00709736  0.01011525  0.01086527  0.01011525  0.00709736
   0.00311849]
 [ 0.00709736  0.01121144  0.00615637  0.0003048   0.00615637  0.01121144
   0.00709736]
 [ 0.01011525  0.00615637 -0.02474903 -0.04811319 -0.02474903  0.00615637
   0.01011525]
 [ 0.01086527  0.0003048  -0.04811319 -0.08285867 -0.04811319  0.0003048
   0.01086527]
 [ 0.01011525  0.00615637 -0.02474903 -0.04811319 -0.02474903  0.00615637
   0.01011525]
 [ 0.00709736  0.01121144  0.00615637  0.0003048   0.00615637  0.01121144
   0.00709736]
 [ 0.00311849  0.00709736  0.01011525  0.01086527  0.01011525  0.00709736
   0.00311849]]


In [16]:
kernel = np.array([[-1, -1, 0], [-1, 0, 1], [0, 1, 1]]) # kernel에 원하는 필터 입력
print(kernel)
img = cv2.filter2D(src, cv2.CV_32F, kernel)
cv2.imshow('src', src)
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

[[-1 -1  0]
 [-1  0  1]
 [ 0  1  1]]
