# Histogram Backprojection

In [1]:
import cv2
import numpy as np

In [2]:
src = np.array([[0, 0, 0, 0],
                [1, 1, 3, 5],
                [6, 1, 1, 3],
                [4, 3, 1, 7]
                ], dtype=np.uint8)

hist = cv2.calcHist(images=[src], channels=[0], mask=None,
                   histSize=[4], ranges=[0, 8])

print('hist =', hist)

backP = cv2.calcBackProject([src], [0], hist, [0, 8], scale=1) # 역투영화
print('backP = ', backP)

hist = [[9.]
 [3.]
 [2.]
 [2.]]
backP =  [[9 9 9 9]
 [9 9 3 2]
 [2 9 9 3]
 [2 3 9 2]]


In [8]:
#1
src = cv2.imread('./data/fruits.jpg')
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(hsv)

#2
roi = cv2.selectROI(src)
print('roi =', roi)
roi_h = h[roi[1]:roi[1]+roi[3], roi[0]:roi[0]+roi[2]]
hist = cv2.calcHist([roi_h], [0], None, [64], [0, 256])
backP = cv2.calcBackProject([h.astype(np.float32)], [0], hist, [0, 256], scale=1.0)
## minVal, maxVal, minLoc, maxLoc = cv2.minMaxLoc(backP)
## T = maxVal - 1 # threshold

#3
hist = cv2.sort(hist, cv2.SORT_EVERY_COLUMN+cv2.SORT_DESCENDING)
k = 1 # tight 하게 만드려면 0으로 설정
T = hist[k][0] - 1 # threshold
print('T =', T)
ret, dst = cv2.threshold(backP, T, 255, cv2.THRESH_BINARY)

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

roi = (396, 164, 72, 73)
T = 744.0
