#  ROI
---

In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

(h, w) = img.shape
print(h, w)

(cy, cx) = (h // 2, w // 2)
print(cy, cx)

roi = img[0:cy, 0:cx]

cv2.imshow('ROI', roi)
cv2.waitKey()
cv2.destroyAllWindows()

512 512
256 256


In [3]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
dst = np.zeros(src.shape, dtype = src.dtype)

N = 4  # 8, 32, 64
height, width = src.shape   # 그레이스케일 영상
h = height // N
w = width // N
for i in range(N):
    for j in range(N):
        y = i * h
        x = j * w
        roi = src[y:y+h, x:x+w]
        val = cv2.mean(roi)
        print(val)
        dst[y:y+h, x:x+w] = val[0]  # 그레이스케일 영상
        
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

(123.74676513671875, 0.0, 0.0, 0.0)
(137.78948974609375, 0.0, 0.0, 0.0)
(144.8642578125, 0.0, 0.0, 0.0)
(114.6787109375, 0.0, 0.0, 0.0)
(118.6441650390625, 0.0, 0.0, 0.0)
(118.2379150390625, 0.0, 0.0, 0.0)
(160.2237548828125, 0.0, 0.0, 0.0)
(128.29620361328125, 0.0, 0.0, 0.0)
(108.54736328125, 0.0, 0.0, 0.0)
(94.21343994140625, 0.0, 0.0, 0.0)
(116.92889404296875, 0.0, 0.0, 0.0)
(160.38909912109375, 0.0, 0.0, 0.0)
(98.98077392578125, 0.0, 0.0, 0.0)
(87.4166259765625, 0.0, 0.0, 0.0)
(152.8258056640625, 0.0, 0.0, 0.0)
(121.42633056640625, 0.0, 0.0, 0.0)


In [6]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
roi = cv2.selectROI(src) # 마우스로 ROI 설정
print('roi = ', roi)

image = src[roi[1]:roi[1]+roi[3], roi[0]:roi[0]+roi[2]]

cv2.imshow('img', image)
cv2.waitKey()
cv2.destroyAllWindows()

# 마우스로 ROI를 지정 후, SpaceBar/ESC를 누른다.

roi =  (103, 43, 309, 358)


In [7]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
rects = cv2.selectROIs('src', src, False, False)   # ROI 여러 개 지정
print('rects = ', rects)

for r in rects:
    cv2.rectangle(src, (r[0], r[1]), (r[0] + r[2], r[1] + r[3]), 255)
    
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

rects =  [[109 131 136 102]
 [304 109 146 126]
 [ 37 117 114 134]
 [146 375 135  83]
 [183 179 134 117]
 [ 62  76 268 129]
 [167 207 220 176]
 [128  58 159 106]
 [128 247 209 182]
 [167 115 124  90]
 [189 306 170 124]
 [ 91 145 227 142]]
